include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: info
    prefer_const_literals_to_create_immutables: info

linter:
  rules:
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
